services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: pcb-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pcb-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/pcb-netlist-visualizer-validator
      - JWT_SECRET=your_jwt_secret_key_change_in_production
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pcb-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - WDS_SOCKET_HOST=localhost
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongo-data:
