services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: pcb-mongo-prod
    restart: always
    volumes:
      - mongo-data:/data/db
    # No port mapping in production to keep MongoDB private
    # Use environment variables for authentication in production
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: pcb-server-prod
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/pcb-netlist-visualizer-validator?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    # Health check to ensure the API is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: pcb-client-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
    # Health check to ensure the web server is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo-data:
